# Default config for scripts/05_train_encoder.py

cesm_path: ~/scratch/CESM2/monthly
checkpoint_dir: ~/alpine/checkpoints/

model_name: inverted_earth_wide
model_arch: InvertedEarthAE

batch_size: 4
batch_interval: 6 # effective batch size = batch_size * batch_interval
num_workers: 8
prefetch_factor: 2
pin_memory: true

epochs: 4
base_lr: 5e-4
final_lr: 1e-6
grad_accumulation_steps: 4

warmup_steps: 200

device_id: 0

checkpoint_interval: 500 # steps between saving model checkpoints
resume_checkpoint: null # path to .ckpt file or null
resume_step: 0 # starting global step when resuming


rotation_p: 0.5
rotation_lows_deg: [-20,-30]
rotation_highs_deg: [20, 30]
